### ISSUE TITLE
Allow outputting formatted text

### ISSUE THREAD

**Issue by chrahunt** [renfredxh/compilebot#16]
Currently the bot prints the stdout in a code-formatted markdown section. It would be nice if there was an option to have stdout set as the bot comment content directly. For example:

Comment invoking the bot:

> +/u/CompileBot python3 --raw-output
> 
> ```
> print("**test**")
> ```

Bot response:

> **test**

or

> **test**
> <sup>[source](#) | [info](http://www.reddit.com/r/CompileBot/wiki) | [git](https://github.com/renfredxh/compilebot) | [report](http://www.reddit.com/message/compose?to=compilebot&subject=Report%20Abuse&message=--report%20Include%20your%20reason%20for%20reporting%20here.)</sup>

**Comment by renfredxh** [comment]
I don't think this is a good idea. This would allow the bot to ping other users, or do other spammy things it can't do right now with the output being pre-formatted.
