### ISSUE TITLE
Add http monitoring

### ISSUE THREAD

**Issue by renfredxh** [renfredxh/compilebot#8]
Add a flask server in deploy.py that responds 200 OK to help keep tabs on when the bot is up and running.

**Comment by wchill** [comment]
What should the server do other than respond with HTTP 200? Log errors?

**Comment by renfredxh** [comment]
Not sure. It doesn't really need to do anything other than let me use an uptime monitoring service to ping the bot to make sure it's up.

At first I was thinking of integrating a simple Flask app in the deploy script, but actually now that I think of it, installing something like [supervisor.d](http://supervisord.org/index.html) in the Dockerfile might be better since it can restart the process if it crashes and has web monitoring.
